const router = require('express').Router();
const authRoutes = require('./auth.routes');
const userRoutes = require('./user.routes');
const postRoutes = require('./post.routes');
const memoryRoutes = require('./memory.routes');
const commentRoutes = require('./comment.routes');
const likeRoutes = require('./like.routes');
const followRoutes = require('./follow.routes');
const chatRoutes = require('./chat.routes');
const notificationRoutes = require('./notification.routes');
const searchRoutes = require('./search.routes');
const communityRoutes = require('./community.routes');
const generationRoutes = require('./generation.routes');
const eventRoutes = require('./event.routes');
const clubRoutes = require('./club.routes');
const beforeNowRoutes = require('./beforeNow.routes');
const guessWhoRoutes = require('./guessWho.routes');
const onThisDayRoutes = require('./onThisDay.routes');
const albumRoutes = require('./album.routes');
const exploreRoutes = require('./explore.routes');
const savedItemRoutes = require('./savedItem.routes');
const draftRoutes = require('./draft.routes');
const profileRoutes = require('./profile.routes');
const streakRoutes = require('./streak.routes');
const achievementRoutes = require('./achievement.routes');
const badgeRoutes = require('./badge.routes');
const adminRoutes = require('./admin.routes');
const moderationRoutes = require('./moderation.routes');
const recommendationRoutes = require('./recommendation.routes');
const analyticsRoutes = require('./analytics.routes');
const callRoutes = require('./call.routes');

router.use('/auth', authRoutes);
router.use('/users', userRoutes);
router.use('/posts', postRoutes);
router.use('/memories', memoryRoutes);
router.use('/comments', commentRoutes);
router.use('/likes', likeRoutes);
router.use('/follows', followRoutes);
router.use('/chat', chatRoutes);
router.use('/notifications', notificationRoutes);
router.use('/search', searchRoutes);
router.use('/communities', communityRoutes);
router.use('/generations', generationRoutes);
router.use('/events', eventRoutes);
router.use('/clubs', clubRoutes);
router.use('/before-now', beforeNowRoutes);
router.use('/guess-who', guessWhoRoutes);
router.use('/on-this-day', onThisDayRoutes);
router.use('/albums', albumRoutes);
router.use('/explore', exploreRoutes);
router.use('/saved', savedItemRoutes);
router.use('/drafts', draftRoutes);
router.use('/profile', profileRoutes);
router.use('/streaks', streakRoutes);
router.use('/achievements', achievementRoutes);
router.use('/badges', badgeRoutes);
router.use('/admin', adminRoutes);
router.use('/moderation', moderationRoutes);
router.use('/recommendations', recommendationRoutes);
router.use('/analytics', analyticsRoutes);
router.use('/calls', callRoutes);

module.exports = router;
